/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/trl/trainer/ppo_trainer.py:239: UserWarning: No dataset is provided. Make sure to set config.batch_size to the correct value before training.
  warnings.warn(
Traceback (most recent call last):
  File "avaliation.py", line 91, in <module>
    log_saved = {'index':[], 'expr':[], 'reward': [], r2:[]}
NameError: name 'r2' is not defined
Index(['type', 'name', 'expression'], dtype='object')
Working with expression:  2 * x[0] + 3