/home/augusto/miniconda3/envs/sr/lib/python3.8/site-packages/trl/trainer/ppo_trainer.py:239: UserWarning: No dataset is provided. Make sure to set config.batch_size to the correct value before training.
  warnings.warn(
Traceback (most recent call last):
  File "avaliation.py", line 89, in <module>
    rewards_saved, expr_saved, mean, top = []
ValueError: not enough values to unpack (expected 4, got 0)